POST http://localhost/upload-spk-php/upload-log-spk.php HTTP/1.1
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<ZSPK01_BTYPE>
	<IDOC BEGIN="1">
		<EDI_DC40 SEGMENT="1">
			<TABNAM>EDI_DC40</TABNAM>
			<MANDT>110</MANDT>
			<DOCNUM>0000000000002162</DOCNUM>
			<DOCREL>640</DOCREL>
			<STATUS>30</STATUS>
			<DIRECT>1</DIRECT>
			<OUTMOD>2</OUTMOD>
			<IDOCTYP>ZSPK01_BTYPE</IDOCTYP>
			<MESTYP>ZSPK01_MTYPE</MESTYP>
			<SNDPOR>SAPDEV</SNDPOR>
			<SNDPRT>LS</SNDPRT>
			<SNDPRN>DEVCLNT110</SNDPRN>
			<RCVPOR>ZDEMOG</RCVPOR>
			<RCVPRT>LS</RCVPRT>
			<RCVPRN>ZSPK01P</RCVPRN>
			<CREDAT>20250915</CREDAT>
			<CRETIM>122004</CRETIM>
			<SERIAL>20250915122004</SERIAL>
		</EDI_DC40>
		<ZSPK01 SEGMENT="1">
			<USER>SEDP06</USER>
			<FILE_LOK>C:\Users\Hendi\AppData\Local\SAP\SAP GUI\tmp</FILE_LOK>
			<FILE_NAME>SPK.pdf</FILE_NAME>
			<ZSPK01_DTL SEGMENT="1">
				<TPDOC>SPK</TPDOC>
				<NODOC>119821299812</NODOC>
			</ZSPK01_DTL>
		</ZSPK01>
	</IDOC>
</ZSPK01_BTYPE>